version: '3'

services:
  todo-list-web:
    build: ./todo-list-web
    container_name: todo-list-web
    ports:
      - "9001:9000"
    depends_on:
      - todolist-workshop-api
    networks:
      - todolist-workshop

  todolist-workshop-api:
    build: ./todolist-workshop-api
    container_name: todolist-workshop-api
    environment:
      DATABASE_URL: # DATABASE_URL
      SECRET: # SECRET
      SECRET_REFRESH: # SECRET_REFRESH
    ports:
      - "3004:3000"
    depends_on:
      - todolist-db
    networks:
      - todolist-workshop

  todolist-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: # POSTGRES_USER
      POSTGRES_PASSWORD: # POSTGRES_PASSWORD
      POSTGRES_DB: # POSTGRES_DB
    ports:
      - 5437:5432
    networks:
      - todolist-workshop
    volumes:
      - todolist-db-data:/var/lib/postgresql/data

networks:
  todolist-workshop:
    driver: bridge

volumes:
  todolist-db-data:
    name: todolist-db-data