CREATE TABLE USERS (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(256) NOT NULL,
	LOGIN VARCHAR(50) UNIQUE NOT NULL,
	PASSWORD TEXT NOT NULL,
	ROLE VARCHAR(10)[]
);

CREATE TABLE TODOLIST (
	ID_TASK SERIAL PRIMARY KEY,
	NAME_TASK VARCHAR(256),
	ID_USER INTEGER,
	FOREIGN KEY (ID_USER) REFERENCES USERS (ID)
);
